name: Check JSON-RPC docs

on:
  pull_request:
    branches:
      - master
    paths:
      - 'tools/generate_json_rpc_docs.py'
      - 'src/*rpc*.cpp'

jobs:
  check-json-rpc-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./tools/generate_json_rpc_docs.py
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          [[ -z "$(git status --porcelain=v1)" ]] && exit 0
          echo "Please run ./tools/generate_json_rpc_docs.py to regenerate docs/JSON-RPC.md"
          exit 1
